/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Banco;

import java.net.URL;
import javax.swing.ImageIcon;

/**
 *
 * @author NaruHina
 */
public class GUIPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form RegistroNuevo
     */
    public GUIPrincipal() {
        initComponents();
        URL iconURL = getClass().getResource("/Imagenes/ATM.png");
        // iconURL is null when not found
        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());
        //Define 40 como Radio.
        IniSesi.setBorder(new RoundedBorder(20));
        this.setSize(495,430);
        //Esto le pone nombre a la parte de arriba de la consola 
        //this.setIconImage(dibu.imagen.usarImagen("ATM.png"));
        this.setTitle("~ Aplicaciones P/Comunicaciones Red ~ Proyecto Final ~");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Registrarse = new javax.swing.JButton();
        IniSesi = new javax.swing.JButton();
        Imagen = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BotonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(null);

        Registrarse.setText("Registrarse");
        Registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarseActionPerformed(evt);
            }
        });
        getContentPane().add(Registrarse);
        Registrarse.setBounds(20, 270, 100, 30);

        IniSesi.setText("Iniciar Sesión");
        IniSesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniSesiActionPerformed(evt);
            }
        });
        getContentPane().add(IniSesi);
        IniSesi.setBounds(230, 180, 120, 30);

        Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cajero.png"))); // NOI18N
        getContentPane().add(Imagen);
        Imagen.setBounds(0, 0, 400, 300);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Letra1.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-430, -20, 830, 350);

        BotonSalir.setText("Salir");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(BotonSalir);
        BotonSalir.setBounds(400, 350, 80, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IniSesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniSesiActionPerformed
        //Nueva instancia de Iniciar Sesión
        Iniciar in = new Iniciar();
        in.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_IniSesiActionPerformed

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        //Salirse del programa
        System.exit(0);
    }//GEN-LAST:event_BotonSalirActionPerformed

    private void RegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarseActionPerformed
       //Abre la nueva ventana para rellenar las credenciales
       //Se hace una nueva instancia de el nuevo JFRAME que en este caso será registrarse
       Registrarse RG=new Registrarse();
       RG.setVisible(true);
       this.dispose(); //se cierra el JFRAME de GUIPRINCIPAL
      
    }//GEN-LAST:event_RegistrarseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonSalir;
    private javax.swing.JLabel Imagen;
    private javax.swing.JButton IniSesi;
    private javax.swing.JButton Registrarse;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
