/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Banco;

import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author NaruHina
 */
public class Iniciar extends javax.swing.JFrame {

    /**
     * Creates new form Iniciar
     */
     Connection buscar;
    public Iniciar() {
        
        initComponents();
        URL iconURL = getClass().getResource("/Imagenes/Registro.jpg");
        // iconURL is null when not found
        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());
        //IniSesi.setBorder(new RoundedBorder(20));
        this.setSize(310,350);
        //Esto le pone nombre a la parte de arriba de la consola 
        //this.setIconImage(dibu.imagen.usarImagen("ATM.png"));
        this.setTitle("~ Log In ~  ACR");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EtiquetaCorreo = new javax.swing.JLabel();
        Correito = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        BtnIngresar = new javax.swing.JButton();
        Password = new javax.swing.JPasswordField();
        Icono = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        EtiquetaCorreo.setText("Correo Electrónico");
        getContentPane().add(EtiquetaCorreo);
        EtiquetaCorreo.setBounds(80, 50, 110, 30);

        Correito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CorreitoKeyTyped(evt);
            }
        });
        getContentPane().add(Correito);
        Correito.setBounds(50, 90, 180, 30);

        jLabel1.setText("Contraseña");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 160, 80, 20);

        Titulo.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        Titulo.setText("Inicia Sesión");
        getContentPane().add(Titulo);
        Titulo.setBounds(90, 0, 110, 40);

        BtnIngresar.setText("Ingresar");
        BtnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnIngresar);
        BtnIngresar.setBounds(160, 230, 80, 30);

        Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PasswordKeyTyped(evt);
            }
        });
        getContentPane().add(Password);
        Password.setBounds(100, 190, 60, 30);

        Icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogIn.png"))); // NOI18N
        getContentPane().add(Icono);
        Icono.setBounds(20, 20, 310, 260);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CorreitoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CorreitoKeyTyped
       int limite  = 30;
     if (Correito.getText().length() == limite){
         evt.consume();
         
         JOptionPane.showMessageDialog(rootPane, "Limite de caracteres excedido");
     }
    }//GEN-LAST:event_CorreitoKeyTyped

    private void PasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordKeyTyped
     int limite  = 8;
     if (Password.getText().length() == limite){
         evt.consume();
         JOptionPane.showMessageDialog(rootPane, "La contraseña tiene un tamaño unicamente de 8 caracteres");
     }
    }//GEN-LAST:event_PasswordKeyTyped

    private void BtnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIngresarActionPerformed

    if (BtnIngresar.getText().equals("Ingresar")) {
          String user = Correito.getText(); //Agarrar lo de las cajas de texto de correo y contraseña
          String contra = Password.getText();
        if(Correito.getText()!=null && Password.getText()!= null){  
            try {
                buscar = DriverManager.getConnection("jdbc:mysql://localhost/rdrr","root","");
                String SQL = "SELECT * FROM clientes WHERE correo=? and contraseña=?";
               // String Concat = "Select CONCAT(Nombre, ApellidoPaterno, ApellidoMaterno) As Nombre From clientes WHERE idClientes = ?";
                PreparedStatement pst = buscar.prepareStatement(SQL);
                pst.setString(1,user);
                pst.setString(2,contra);
                ResultSet rs = pst.executeQuery();
                
                //Me tarde un buen rato para lograr que saliera el nombre personalizado TuT 
                String SQL1= "Select CONCAT(Nombre, ' ', ApellidoPaterno) As Nombre From Clientes where correo=? and contraseña=?;";
                PreparedStatement ps1 = buscar.prepareStatement(SQL1);
                ps1.setString(1,user);
                ps1.setString(2,contra);
                ResultSet rs1 = ps1.executeQuery();
                 if(rs.next() && rs1.next()){
                     String is = rs1.getString("Nombre");
                     JOptionPane.showMessageDialog(null,"¡ Bienvenido nuevamente !"+"\n"+is);
                   //  System.out.printf("%s",is);
                        setVisible(false);
                        Bienvenido Bd = new Bienvenido();
                        Bd.setVisible(true);
                }else{
                      JOptionPane.showMessageDialog(null,"El correo y/o contraseña son inválidos, favor de intentarlo nuevamente");
                      Correito.setText("");
                      Password.setText("");
                 }
            
                //Statement st = buscar.createStatement(); //Crear el statement
                //st.executeQuery("SELECT COUNT(idClientes) AS i FROM clientes WHERE correo = '"+user+"'"+"AND contraseña='"+contra+"'");
        } catch (SQLException ex) {
            ex.printStackTrace();
            //Si no se logra conectar
            JOptionPane.showMessageDialog(null,"No se pudo conectar a la base de datos");
        }
        }   
       }else{
            JOptionPane.showMessageDialog(null,"Rellene los campos");
    }
    }//GEN-LAST:event_BtnIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Iniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Iniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Iniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Iniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Iniciar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnIngresar;
    private javax.swing.JTextField Correito;
    private javax.swing.JLabel EtiquetaCorreo;
    private javax.swing.JLabel Icono;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
